#!/bin/sh

OPENRESTY_VERSION="1.15.8.3"
LUAROCKS_VERSION="3.3.1"
LUA_VERSION="5.1.5"
LIBRESSL_VERSION="3.0.2"
NGINX_RTMP_MODULE_VERSION="master"
NGINX_HTTP_FLV_MODULE_VERSION="master"
STREAM_ECHO_NGINX_MODULE_VERSION="master"
NGX_LUA_IPC_VERSION="master"
NCHAN_VERSION="master"
LUA_IO_VERSION="master"

stream_echo_path="stream-echo-nginx-module-${STREAM_ECHO_NGINX_MODULE_VERSION}"
rtmp_path="nginx-rtmp-module-${NGINX_RTMP_MODULE_VERSION}"
flv_path="nginx-http-flv-module-${NGINX_HTTP_FLV_MODULE_VERSION}"
ngx_lua_ipc_path="ngx_lua_ipc-${NGX_LUA_IPC_VERSION}"
nchan_path="nchan-${NCHAN_VERSION}"
lua_io_path="lua-io-nginx-module-${LUA_IO_VERSION}"
